### ISSUE TITLE
Missing dependency python-mako

### ISSUE THREAD

**Issue by zeroepoch** [NVIDIA/tegra-nouveau-rootfs#29]
You need to install `python-mako` on Ubuntu 14.04 in order to finish the step `./scripts/build-mesa`.  Maybe this is a new requirement?

**Comment by Gnurou** [comment]
Indeed, it is a requirement - it was actually listed for Arch Linux. I do not really keep up-to-date with Ubuntu requirements since I am not using it, so you reporting these errors is quite helpful. Thanks.

Incidentally, I think you don't even need to compile libdrm and Mesa anymore since the upstream packages now contain all the necessary patches. I will confirm and update the README accordingly.

**Comment by zeroepoch** [comment]
I haven't had a chance to test booting the image I created (will do so tomorrow), but with this and a few other changes I reported it successfully builds each of the steps in the README as of today.  Cool that more of the changes are going upstream.

**Comment by Gnurou** [comment]
Yeah, eventually we want these scripts to become unneeded, excepted maybe for the people who want to easily cross-compile and boot over a network share.

**Comment by Gnurou** [comment]
Oops, correction: libdrm still needs to be compiled due to an extra option that is not enabled on Arch Linux. Stock Mesa is fine though.
